### ISSUE TITLE
Design Notes 10-26

### ISSUE THREAD

**Issue by budparr** [Frontmatter/brooklinebooksmith#16]
Hi @shuchibooksmith

So the first thing I think you'll notice is the color scheme. You'll note the color scheme is quite bright. Look below for a dark version (just the banner color) just to see some of the directions I've been considering. 

You'll also note that I've added color in the sidebars too. I think I might make those so they're various colors on different pages.

Once you get down to the events (on the events page), the bright colors can start to look chaotic mixed with the book covers, so I've darkened them a bit, but I'll probably fool around with that.

Events have been crazy to design for in a programattic way, accounting for varying length titles, the potential for multiple books, etc.

So, you'll note a couple of your requests not present. 
- I haven't added the genre, but only because I was trying to get the overall styling in place. I'll likely do this today.
- The bold author name with non-bold sentence/book title. I haven't figured out how to do this yet while still using a strong typeface. working on it.
- Ticketed Events button. I'll work on that next too.

When I tried a version with part of the data hidden in a tab, it felt like we were asking people to do a lot of clicking to get vital information, so for now I've stuck with showing everything, with the goal of being browsability.

I have two versions. One with the sidebar with data and then, the others (with two different color versions), without the sidebar. Hope I'm not making things too confusing for you with all these versions!

Light (two/three columns of events): [http://brookline-151026-1341-two-column-events.surge.sh]

dark (three columns of events): [http://brookline-151026-1308.surge.sh]

light (three columns of events): http://brookline-151026-1341.surge.sh/

**Comment by shuchibooksmith** [comment]
Wonderful! Will have comments for you in a couple of days. Would you prefer I start new issue threads for comments, or include them in one big chunk of text here?

**Comment by budparr** [comment]
Probably just put him here and if separate issues arise out of them we can then start a new issue.

**Comment by shuchibooksmith** [comment]
HI, Bud!

-So I think we all prefer a horizontal layout as opposed to the square cards. Mainly, it doesn't feel organic to chronology, and it looks a bit too academic. If we use a horizontal layout, I know this brings up issues of scrolling, and customers having to scroll quite a bit to get to see all of the events, but if an event "expires" after it's past, scrolling shouldn't be too much of an issue. The placeholder you currently have for Storytime at the bottom of the page - this is closer to the size we were thinking for each event. It won't look all that different from what we have on our page now, it will just be delineated by a box and cleaner.

-We are asking folks to do a lot of click with the tab format, but there is a lot of changing information for each event.  I think most people will ignore the basic information in the bar on the right - I didn't even know that information was available on our current events page until just recently. And since information does vary from event to event, we're going to have to add all of that info into the space for each event. 

-any thoughts on the calendar icon linking to google calendar for each event?

-progress on the ticket events icon?

**Comment by budparr** [comment]
Good feedback and we'll keep pushing on the design. 

So you want the information that I have in the sidebar repeated for each event (the in-store block for in-store events, Coolidge event info where appropriate)?

I'll have both of the last two items in the next version.

**Comment by shuchibooksmith** [comment]
Yes, so for in-store events it would look like this
This event is in downstairs in our Writers and Readers Room and is free and open to the public.Seating begins at 6:30pm. Our downstairs event space is not handicapped accessible; if you need further assistance please call ahead of time for accommodation at (617) 566-6660.

If you can't make it to one of our excellent events, you may order signed copies of events books by calling the store at (617) 566-6660 or by ordering the book through our website. Just click "Shop Online" and request a signature and/or inscription in the "Additional Comments" field at checkout. Personalization is at author's discretion and not guaranteed.

And ticketed events:
This event is at the Coolidge Corner Theatre. Tickets are $5 or free with purchase of the book. Purchase tickets by visiting brooklinebooksmith.com/tickets or calling the store at (617) 566-6660.
-Line to enter the theatre begins at 5:30pm
-Seating begins at 5:45pm
-For sold out events: after 5:55pm, latecomers will be seated at the discretion of the theatre.

**Comment by budparr** [comment]
Cool, I get it now.
