### ISSUE TITLE
Carousel cards

### ISSUE THREAD

**Issue by shuchibooksmith** [Frontmatter/brooklinebooksmith#18]
Thoughts on a 2.5 card view in carousel instead of current 3.5?

**Comment by budparr** [comment]
That depends. Some things to keep in mind:

- The # of cards changes per viewport, so on smaller screens there are indeed already fewer cards (when I design I'm constantly looking at about a dozen viewports). 

- The card-design is meant so that if you don't have images you can just throw a bit of copy in there, which I think is particularly useful because you're going to want to keep that fresh (The solid cards also break up the noise of having a bunch of images in there). If you make those cards very large that tactic won't work because the cards will look barren with just copy.

- It's really hard to come up with high quality images, and that gets harder the larger they are (book covers aren't going to be good here).   
One of the things I have to think about when designing is the available resources for adding content and I try to make things so there's no great onus on you to have a photoshop expert on staff at all times. 

- Larger cards will push the content down further, particularly on smaller screens, which means that part of your audience may never see it.

Maybe your concern about the cards' size really means that you don't like the carousel at all?

**Comment by shuchibooksmith** [comment]
I don't think that it's that we don't like the carousel. I think it's more Lisa referring to Albertine's, which is a website she just finds near perfect. Their carousel shows 1.5 images at a time.
http://albertine.com/

That being said, your points are all incredibly valid. Especially because we would want to use book jackets or images from the publisher. We won't be taking too many of our own photos. 

Maybe a solution would be messing with margins some more. The carousel doesn't have any margins, and maybe, with a white border, the carousel images don't need to extend from end to end??

**Comment by budparr** [comment]
fwiw, Albertine may not be the best comp, only because they're entire look and feel is going for something different than you.

**Comment by shuchibooksmith** [comment]
i think so too, though i think lisa loves the albertine's website so much (in some ways i think she just wants us to basically have that site) that i've been trying to figure out what exactly she loves about their website and whether or not it's viable for our site. we are different from albertine's in overall personality. they are much more sophisticated and refined, both in store and on the site; we have a lot more going on, many more moving parts, and though lisa wants to push the store in the realm of more sophisticated, we are always going to have a funkier personality, i think. this all goes into a larger discussion about the overall vision for the store, which is different from owner to owner. sigh. so what i'm representing/advocating for with you, hopefully, is some sort of marriage of the two. sophisticated but also fun; streamlined but not boring. 
it's hard.

**Comment by budparr** [comment]
I could tell you some (un)fun stories about designing for the fine line between people's impressions of their organization and what the outside world sees. 

But, at any rate, it would be a mistake to design to another site's design. We have to stake out your own personality. Your readers probably would be happy with some plain text! Seriously - the best thing we can do for them is to not get in the way. We have to keep that in mind and not overdesign to what we perceive is going to be the impression of your organization derived from a visit to the site.

Don't worry though - we'll get there, and remember this can all evolve. We don't have to get it just perfect right away.

**Comment by shuchibooksmith** [comment]
I figured you would understand. I totally agree that we have to stake out our own personality, however challenging that may be. And it is really coming along. The fact that we don't have to get it perfect right away is a huge relief.
